
const tintColorLight = '#2C5F2D';
const tintColorDark = '#F5EDD1';

export default {
  light: {
    text: '#2C5F2D',
    background: '#F5EDD1',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primary: '#2C5F2D',
    primaryForeground: '#FFFFFF',
    secondary: '#FFFFFF',
    secondaryForeground: '#2C5F2D',
    muted: '#F5EDD1',
    mutedForeground: 'rgba(44, 95, 45, 0.6)',
    accent: '#E5E5E5',
    accentForeground: '#2C5F2D',
    destructive: '#d4183d',
    border: 'rgba(0, 0, 0, 0.1)',
    card: '#FFFFFF',
    cardForeground: '#2C5F2D',
    rating: '#e4b30e',
  },
  dark: {
    text: '#F5EDD1',
    background: '#2C5F2D',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    primary: '#F5EDD1',
    primaryForeground: '#2C5F2D',
    secondary: '#2C5F2D',
    secondaryForeground: '#F5EDD1',
    muted: '#2C5F2D',
    mutedForeground: 'rgba(245, 237, 209, 0.6)',
    accent: '#E5E5E5',
    accentForeground: '#2C5F2D',
    destructive: '#d4183d',
    border: 'rgba(255, 255, 255, 0.1)',
    card: '#2C5F2D',
    cardForeground: '#F5EDD1',
    rating: '#e4b30e',
  },
};
